function createfigure(YMatrix1)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 11-Nov-2015 02:57:38

% Create figure
figure1 = figure('Name','As Execution Time for each execution');
colormap('jet');

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on','XGrid','on',...
    'Color',[0.933333337306976 0.933333337306976 0.933333337306976]);
box(axes1,'on');
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'LineWidth',3,'Parent',axes1);
set(plot1(1),'DisplayName','AS\_ExecTimeExc(1)');
set(plot1(2),'DisplayName','AS\_ExecTimeExc(2)');
set(plot1(3),'DisplayName','AS\_ExecTimeExc(3)');
set(plot1(4),'DisplayName','AS\_ExecTimeExc(4)');
set(plot1(5),'DisplayName','AS\_ExecTimeExc(5)');


% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.16846451899238 0.594524062868553 0.220899466523733 0.280875298153811],...
    'Color',[1 1 1]);

