fig2 = figure;hold on;        
figname1 = ['figCumuEmpPr','s',char(pcstr),'s',char(pmstr)];
title(['Cum. emp. prob. with P_{crossover}= ',num2str(pc),', P_{mutation}= ',num2str(pm),', generation= ',num2str(g_max),])
h1 = plot([1:g_max],vect_cnt_opt,'LineWidth',2,...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor','g',...
    'MarkerSize',.2);
h2 = plot([1:g_max],vect_rel_dist1,'LineWidth',2,...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor','b',...
    'MarkerSize',.2);hold on

h3 = plot([1:g_max],vect_rel_dist2,'LineWidth',2,...
    'MarkerEdgeColor','r',...
    'MarkerFaceColor','r',...
    'MarkerSize',.2);   
legend([h1 h2 h3],'op','Relative distance to optimum = 1.0 %','Relative distance to optimum = 2.5 %','Location','best')
hold off
print(fullfile(fnamefigures,figname1),'-depsc')
print(fullfile(fnamefigures,figname1),'-djpeg')
fignametosave1 = [char(figname1),'.fig'];
savefig(fig2,fullfile(fnamefigures,fignametosave1),'compact');
